
version: '2'
services:

  redis_nginx:
    build: ./nginx/
    image: redis_nginx-img:0.0.1
    container_name: redis_nginx
    hostname: redis_nginx
    network_mode: "host"
    #networks:
    #    - vlan
    depends_on:
        - redis_php.fpm73
    volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf/conf.d:/etc/nginx/conf.d
        - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ./www:/www
        - ./logs:/var/log/nginx
        - "phpsocket:/var/run"
    restart: always
    ports:
        - 16379:16379

  redis_php.fpm73:
    build: ./php-fpm73/
    image: redis_php.fpm73-img:0.0.1
    container_name: redis_php.fpm73
    hostname: redis_php.fpm73
    network_mode: "host"
    #networks:
    #    - vlan
    #extra_hosts:
    #    - redis:127.0.0.1
    volumes:
        - ./php-fpm73/conf:/usr/local/etc/php-fpm.d
        - ./php-fpm73/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./www:/www
        - "phpsocket:/var/run"
    restart: always
    # ports:
    #     - 9000:9000

  redis:
    build: ./redis/
    image: redis-img:0.0.1
    container_name: redis
    hostname: redis
    network_mode: "host"
    #networks:
    #    - vlan
    volumes:
        - ./redis/data:/data
        - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
        - 6379:6379

#networks:
#  vlan:
volumes:
    phpsocket:      
